### PR TITLE
Fix issues with parsing and emitting EDN characters

### LINKED ISSUE #4: Chars are not printed with a leading backslash
From the edn spec:
```
Characters are preceded by a backslash: \c, \newline, \return, \space and \tab yield the corresponding characters. Unicode characters are represented with \uNNNN as in Java. Backslash cannot be followed by whitespace
```

But if I print the Character "c", I just get "c", not "\c".

### PR DESCRIPTION
**Pull request by skyrod-vactai**
Fixes #4, #5. All the tests pass (including a few extra asserts I added), so hopefully it's not breaking anything.

### CODE REVIEW

**Comment by bowbahdoe** [comment]
@skyrod-vactai Hi - can you clarify what issues this is solving?

**Comment by bowbahdoe** [comment]
nevermind - i see the linked issues. Can you fix the failing lints?

**Comment by skyrod-vactai** [comment]
Thanks for looking at this @bowbahdoe ! I fixed the 2 lint errors that I caused. The other ones appear to be in the existing code. 

The coverage error, I am not sure what that's about, it doesn't appear to be caused by my PR either:

```
  Installing /home/runner/.cargo/bin/cargo-tarpaulin
   Installed package `cargo-tarpaulin v0.27.0` (executable `cargo-tarpaulin`)
error: invalid value 'Xml' for '--out [<FMT>...]'
  [possible values: json, stdout, xml, html, lcov]

  tip: a similar value exists: 'xml'
```

**Comment by bowbahdoe** [comment]
@skyrod-vactai I published a new version. `3.3.0` which includes this change

**Comment by skyrod-vactai** [comment]
Thanks! Will upgrade and try it out.

**Pull request merged**
